name: watch_list
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

  
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^1.2.0
  shared_preferences: ^2.2.3
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  animate_do: ^3.3.4
  another_flutter_splash_screen: ^1.2.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  palette_generator: ^0.3.3+3
  carousel_slider: ^4.2.1
  drop_down_list: ^0.0.6
  intl: ^0.19.0
  package_info_plus: 5.0.1 
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/loading1.gif
    - assets/gifs/loading2.gif
    - assets/gifs/loading3.gif
    - assets/pngs/background1.png
    - assets/pngs/background2.png
    - assets/pngs/background3.png
    - assets/pngs/background4.png
    - assets/pngs/background5.png
    - assets/pngs/background6.png
    - assets/pngs/background7.png
    - assets/pngs/background8.png
    - assets/pngs/background9.png
    - assets/pngs/background10.png
    - assets/pngs/background11.png
    - assets/pngs/background12.png
    - assets/pngs/background13.png
    - assets/pngs/background14.png
    - assets/pngs/background15.png

    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
